### ISSUE TITLE
Errors encountered in indicated sections + resolutions

### ISSUE THREAD

**Issue by viewsdevelop** [learn-co-curriculum/python-p3-crud-with-sqlalchemy#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/create-read-update-and-delete-with-sqlalchemy?module_item_id=468028

### Concern

General Note - Appears necessary to first issue `pip install flask_sqlalchemy` in order to run `python lib/sqlalchemy_sandbox.py` 

---

1. **"Refactoring Our Schema"** - `NameError: name 'create_engine' is not defined`

2. **"Creating Records"** - `NameError: name 'sessionmaker' is not defined`

3. **"Creating Records"** - `NameError: name 'Student' is not defined`

4. **"Read Records"** - `IndentationError: unexpected indent`

5. **"Selecting Only Certain Columns"** - `IndentationError: unexpected indent`

6. **"Ordering"** - `IndentationError: unexpected indent`

7. **"Limiting"** - `IndentationError: unexpected indent`

8. **"`func`"** - `IndentationError: unexpected indent`

9. **"Filtering"** - `IndentationError: unexpected indent`

10. **"Updating Data"** - `IndentationError: unexpected indent`

11. **"Deleting Data"** - `IndentationError: unexpected indent` 

### Suggested Changes

To fix Errors 1 + 2, add the following imports in `sqlalchemy_sandbox.py`:

`from sqlalchemy import create_engine`
`from sqlalchemy.orm import sessionmaker`

To fix Error 3, remove unnecessary indentation across all lines of code snippet(s).

To fix Errors 4 - 11, remove unnecessary indentation across all lines of code snippet(s).

**Comment by professor-ben** [comment]
didn't do *exactly* this, but updated the Pipfile, added imports to sqlalchemy_sandbox.py, and made abundantly clear that if/name/main starts indented code blocks
