### ISSUE TITLE
Several errors in the instructions for CRUD with AQLAlchemy

### ISSUE THREAD

**Issue by Fakishki** [learn-co-curriculum/python-p3-crud-with-sqlalchemy#10]
### Canvas Link

https://learning.flatironschool.com/courses/6274/pages/create-read-update-and-delete-with-sqlalchemy?module_item_id=554161

### Concern

Take a look at the text from the "Limiting" section onward.

`# imports, models

if __name__ == '__main__':

    # create session, student objects

    oldest_student = session.query(
            Student.name, Student.birthday).order_by(
            desc(Student.grade)).limit(1).all()

    print(oldest_student)

# => [('Alan Turing', datetime.datetime(1912, 6, 23, 0, 0))]`

This should be "desc(Student.birthday)" not "desc(Student.grade)"

And the logic is flawed.  The method we're using to retrieve the oldest student is actually returning the student with the highest/largest/latest year, which would give us the youngest student, not the oldest one.

**Comment by professor-ben** [comment]
Hi Wally,

It looks like we're sorting for the student with the highest grade, which would give us one of the older students. This logic does not guarantee the oldest student if there are multiple in a single grade, though. I'll fix this later today.

Thanks,
Ben

**Comment by Fakishki** [comment]
Hi Ben!  I understand what you're saying.  I can tell you, though, that as
someone who's going through this curriculum for the first time, the fact
that we're trying to measure oldest by grade level, when one of the only
other attributes we're tracking is age based on birthday, seems kinda
counterintuitive from the student's standpoint.

I also spotted a few grammar/sentence errors in that particular lesson.

Not harping on y'all.  I know this is new material.  I've just been trying
to help point out the little things I find to help y'all refine it.  Have
an awesome week!

**Comment by professor-ben** [comment]
Of course. I appreciate any feedback that helps improve the curriculum.
