### ISSUE TITLE
Why have "name" in constraints?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-crud-with-sqlalchemy#6]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/create-read-update-and-delete-with-sqlalchemy?module_item_id=468028

### Concern

Could we briefly drop in a description as to why our contraints also take a "name" property? Or maybe just delineate what the arguments we pass to a constraint are and why we pass them? I can see this being a sticking point for students at the moment.

**Comment by professor-ben** [comment]
We added a module on constraints later on in Phase 4, so I think we're safe removing constraints from this earlier lesson to begin with. I'll get on that soon.

**Comment by Matt-Eva** [comment]
Sounds good, thanks!
