### ISSUE TITLE
Include the need to run pipenv install and pipenv shell before running any other commands

### ISSUE THREAD

**Issue by sheenasany** [learn-co-curriculum/python-p3-crud-with-sqlalchemy#9]
### Canvas Link

https://github.com/learn-co-curriculum/python-p3-defining-schema-with-sqlalchemy

### Concern

I worry that students may not run the `pipenv install` and `pipenv shell` prior to running 
`chmod +x app/sqlalchemy_sandbox.py`

Perhaps adding this to the curriculum could help clarify to students that they need to run those essential commands first before continuing on with the lab.

**Comment by professor-ben** [comment]
Great point- this has been addressed in the new commit and will be reflected in Canvas upon the next sync.

-Ben
